# Generated by Django 5.1.4 on 2025-07-04 12:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('alternate_mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='staff/profile_images/')),
                ('pant', models.BooleanField(default=False)),
                ('shoe', models.BooleanField(default=False)),
                ('grooming', models.BooleanField(default=False)),
                ('experienced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_details', to='users.user')),
            ],
        ),
    ]
