# Generated by Django 5.1.4 on 2025-07-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_created_at_staffdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdetails',
            name='name',
        ),
    ]
