# Generated by Django 5.1.4 on 2025-07-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_staffdetails_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('subadmin', 'Subadmin/Captain'), ('supervisor', 'Supervisor'), ('head_boy', 'Head_boy'), ('boys', 'Boys')], max_length=20),
        ),
    ]
