# Generated by Django 5.1.4 on 2025-07-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_type', models.CharField(choices=[('boys', 'Boys'), ('vice_supervisor', 'Vice Supervisor'), ('supervisor', 'Supervisor'), ('captain', 'Captain'), ('setting', 'Setting'), ('loading', 'Loading')], max_length=30, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
