# Generated by Django 5.1.4 on 2025-07-05 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_boyrating_dailywage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('place', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('work_type', models.CharField(choices=[('wedding', 'Wedding'), ('corporate', 'Corporate Event'), ('private', 'Private Party'), ('others', 'Others')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('no_of_boys_needed', models.PositiveIntegerField(default=0)),
                ('attendees', models.PositiveIntegerField(default=0)),
                ('location_url', models.URLField(blank=True, help_text='Paste Google Maps link of the venue location', max_length=500, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_boys', models.ManyToManyField(blank=True, limit_choices_to={'role': 'boys'}, related_name='assigned_works', to=settings.AUTH_USER_MODEL)),
                ('assigned_supervisor', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['supervisor', 'vice_supervisor', 'subadmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_works', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
